-- lid: DuckDB target, generated by idgen from lid.yaml. Do not edit.
-- width 128, epoch 1970-01-01T00:00:00Z, value type UHUGEINT

CREATE OR REPLACE MACRO lid_encode(in_ts_ms, in_layer, in_experiment, in_file, in_run, in_channel, in_segment, in_radioactive) AS CASE WHEN in_ts_ms NOT BETWEEN 0 AND 281474976710655 THEN error('lid_encode: ts_ms out of range, 0 to 281474976710655') WHEN in_layer NOT BETWEEN 0 AND 15 THEN error('lid_encode: layer out of range, 0 to 15') WHEN in_experiment NOT BETWEEN 0 AND 255 THEN error('lid_encode: experiment out of range, 0 to 255') WHEN in_file NOT BETWEEN 0 AND 65535 THEN error('lid_encode: file out of range, 0 to 65535') WHEN in_run NOT BETWEEN 0 AND 15 THEN error('lid_encode: run out of range, 0 to 15') WHEN in_channel NOT BETWEEN 0 AND 1023 THEN error('lid_encode: channel out of range, 0 to 1023') WHEN in_segment NOT BETWEEN 0 AND 1023 THEN error('lid_encode: segment out of range, 0 to 1023') WHEN in_radioactive NOT BETWEEN 0 AND 1 THEN error('lid_encode: radioactive out of range, 0 to 1') ELSE CAST(in_ts_ms AS UHUGEINT) * CAST(1208925819614629174706176 AS UHUGEINT) + CAST(in_layer AS UHUGEINT) * CAST(75557863725914323419136 AS UHUGEINT) + CAST(in_experiment AS UHUGEINT) * CAST(295147905179352825856 AS UHUGEINT) + CAST(in_file AS UHUGEINT) * CAST(281474976710656 AS UHUGEINT) + CAST(in_run AS UHUGEINT) * CAST(17592186044416 AS UHUGEINT) + CAST(in_channel AS UHUGEINT) * CAST(17179869184 AS UHUGEINT) + CAST(in_segment AS UHUGEINT) * CAST(16777216 AS UHUGEINT) + CAST(in_radioactive AS UHUGEINT) * CAST(8388608 AS UHUGEINT) END;

CREATE OR REPLACE MACRO lid_ts_ms(x) AS CAST((CAST(x AS UHUGEINT) >> 80) & 281474976710655 AS BIGINT);
CREATE OR REPLACE MACRO lid_layer(x) AS CAST((CAST(x AS UHUGEINT) >> 76) & 15 AS BIGINT);
CREATE OR REPLACE MACRO lid_experiment(x) AS CAST((CAST(x AS UHUGEINT) >> 68) & 255 AS BIGINT);
CREATE OR REPLACE MACRO lid_file(x) AS CAST((CAST(x AS UHUGEINT) >> 48) & 65535 AS BIGINT);
CREATE OR REPLACE MACRO lid_run(x) AS CAST((CAST(x AS UHUGEINT) >> 44) & 15 AS BIGINT);
CREATE OR REPLACE MACRO lid_channel(x) AS CAST((CAST(x AS UHUGEINT) >> 34) & 1023 AS BIGINT);
CREATE OR REPLACE MACRO lid_segment(x) AS CAST((CAST(x AS UHUGEINT) >> 24) & 1023 AS BIGINT);
CREATE OR REPLACE MACRO lid_radioactive(x) AS CAST((CAST(x AS UHUGEINT) >> 23) & 1 AS BIGINT);

CREATE OR REPLACE MACRO lid_decode(x) AS {"ts_ms": lid_ts_ms(x), "layer": lid_layer(x), "experiment": lid_experiment(x), "file": lid_file(x), "run": lid_run(x), "channel": lid_channel(x), "segment": lid_segment(x), "radioactive": lid_radioactive(x)};
CREATE OR REPLACE MACRO lid_validate(x, expected_layer) AS lid_layer(x) = expected_layer;
CREATE OR REPLACE MACRO lid_relayer(x, from_layer) AS CASE WHEN NOT lid_validate(x, from_layer) THEN error('lid_relayer: layer bits do not match from_layer') WHEN from_layer >= 15 THEN error('lid_relayer: no layer above 15') ELSE CAST(x AS UHUGEINT) + (CAST(1 AS UHUGEINT) << 76) END;
CREATE OR REPLACE MACRO lid_time(x) AS to_timestamp((lid_ts_ms(x) + 0) / 1000.0);
CREATE OR REPLACE MACRO lid_to_uuid(x) AS CAST(substr(lpad(hex(CAST(x AS UHUGEINT)), 32, '0'), 1, 8) || '-' || substr(lpad(hex(CAST(x AS UHUGEINT)), 32, '0'), 9, 4) || '-' || substr(lpad(hex(CAST(x AS UHUGEINT)), 32, '0'), 13, 4) || '-' || substr(lpad(hex(CAST(x AS UHUGEINT)), 32, '0'), 17, 4) || '-' || substr(lpad(hex(CAST(x AS UHUGEINT)), 32, '0'), 21, 12) AS UUID);
CREATE OR REPLACE MACRO lid_from_uuid(u) AS CAST(CAST(from_hex(replace(CAST(u AS VARCHAR), '-', '')) AS BIT) AS UHUGEINT);
CREATE OR REPLACE MACRO lid_text(x) AS list_aggregate(list_transform(range(26), i -> substr('0123456789ABCDEFGHJKMNPQRSTVWXYZ', ((CAST(x AS UHUGEINT) >> CAST(125 - i * 5 AS UHUGEINT)) & 31)::INTEGER + 1, 1)), 'string_agg', '');
CREATE OR REPLACE MACRO lid_parse(s) AS CASE WHEN length(s) <> 26 THEN error('lid_parse: expected 26 characters') ELSE list_reduce(list_transform(string_split(upper(s), ''), c -> CAST(position(c IN '0123456789ABCDEFGHJKMNPQRSTVWXYZ') - 1 AS UHUGEINT)), (a, d) -> a * 32 + d) END;
