-- lid: DuckDB target, generated by idgen from lid.yaml. Do not edit.
-- width 128, epoch 1970-01-01T00:00:00Z, value type UHUGEINT

CREATE OR REPLACE MACRO lid_encode(in_ts_ms, in_layer, in_experiment, in_file, in_run, in_channel, in_segment, in_radioactive) AS CAST(in_ts_ms AS UHUGEINT) * CAST(1208925819614629174706176 AS UHUGEINT) + CAST(in_layer AS UHUGEINT) * CAST(75557863725914323419136 AS UHUGEINT) + CAST(in_experiment AS UHUGEINT) * CAST(295147905179352825856 AS UHUGEINT) + CAST(in_file AS UHUGEINT) * CAST(281474976710656 AS UHUGEINT) + CAST(in_run AS UHUGEINT) * CAST(17592186044416 AS UHUGEINT) + CAST(in_channel AS UHUGEINT) * CAST(17179869184 AS UHUGEINT) + CAST(in_segment AS UHUGEINT) * CAST(16777216 AS UHUGEINT) + CAST(in_radioactive AS UHUGEINT) * CAST(8388608 AS UHUGEINT);

CREATE OR REPLACE MACRO lid_ts_ms(x) AS CAST((CAST(x AS UHUGEINT) >> 80) & 281474976710655 AS BIGINT);
CREATE OR REPLACE MACRO lid_layer(x) AS CAST((CAST(x AS UHUGEINT) >> 76) & 15 AS BIGINT);
CREATE OR REPLACE MACRO lid_experiment(x) AS CAST((CAST(x AS UHUGEINT) >> 68) & 255 AS BIGINT);
CREATE OR REPLACE MACRO lid_file(x) AS CAST((CAST(x AS UHUGEINT) >> 48) & 65535 AS BIGINT);
CREATE OR REPLACE MACRO lid_run(x) AS CAST((CAST(x AS UHUGEINT) >> 44) & 15 AS BIGINT);
CREATE OR REPLACE MACRO lid_channel(x) AS CAST((CAST(x AS UHUGEINT) >> 34) & 1023 AS BIGINT);
CREATE OR REPLACE MACRO lid_segment(x) AS CAST((CAST(x AS UHUGEINT) >> 24) & 1023 AS BIGINT);
CREATE OR REPLACE MACRO lid_radioactive(x) AS CAST((CAST(x AS UHUGEINT) >> 23) & 1 AS BIGINT);

CREATE OR REPLACE MACRO lid_decode(x) AS {"ts_ms": lid_ts_ms(x), "layer": lid_layer(x), "experiment": lid_experiment(x), "file": lid_file(x), "run": lid_run(x), "channel": lid_channel(x), "segment": lid_segment(x), "radioactive": lid_radioactive(x)};
CREATE OR REPLACE MACRO lid_validate(x, expected_layer) AS lid_layer(x) = expected_layer;
CREATE OR REPLACE MACRO lid_time(x) AS to_timestamp((lid_ts_ms(x) + 0) / 1000.0);
CREATE OR REPLACE MACRO lid_to_uuid(x) AS CAST(CAST(x AS UHUGEINT) AS UUID);
CREATE OR REPLACE MACRO lid_from_uuid(u) AS CAST(CAST(u AS UHUGEINT) AS UHUGEINT);
